app = 'double-zero-db'
primary_region = 'mad'

[build]
  
[mounts]
  source = "pb_data" # name of the volume
  destination = "/pb/pb_data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0